# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Smitty\SoftwareProjects\_pythonScripts\vamTextureOptimizer\Widgets\ProgressDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogProgress(object):
    def setupUi(self, DialogProgress):
        DialogProgress.setObjectName("DialogProgress")
        DialogProgress.resize(272, 339)
        self.formLayout = QtWidgets.QFormLayout(DialogProgress)
        self.formLayout.setObjectName("formLayout")
        self.label_totalprogress = QtWidgets.QLabel(DialogProgress)
        self.label_totalprogress.setObjectName("label_totalprogress")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_totalprogress)
        self.progressBar_totalprogress = QtWidgets.QProgressBar(DialogProgress)
        self.progressBar_totalprogress.setProperty("value", 24)
        self.progressBar_totalprogress.setObjectName("progressBar_totalprogress")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.progressBar_totalprogress)
        self.label_taskprogress = QtWidgets.QLabel(DialogProgress)
        self.label_taskprogress.setObjectName("label_taskprogress")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_taskprogress)
        self.progressBar_taskProgress = QtWidgets.QProgressBar(DialogProgress)
        self.progressBar_taskProgress.setProperty("value", 24)
        self.progressBar_taskProgress.setObjectName("progressBar_taskProgress")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.progressBar_taskProgress)
        self.textbox = QtWidgets.QTextEdit(DialogProgress)
        self.textbox.setEnabled(True)
        self.textbox.setReadOnly(True)
        self.textbox.setObjectName("textbox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.textbox)

        self.retranslateUi(DialogProgress)
        QtCore.QMetaObject.connectSlotsByName(DialogProgress)

    def retranslateUi(self, DialogProgress):
        _translate = QtCore.QCoreApplication.translate
        DialogProgress.setWindowTitle(_translate("DialogProgress", "Dialog"))
        self.label_totalprogress.setText(_translate("DialogProgress", "TextLabel"))
        self.label_taskprogress.setText(_translate("DialogProgress", "TextLabel"))
        self.textbox.setHtml(_translate("DialogProgress", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
